# Generated by Django 4.0 on 2026-03-06 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0002_user_avatar_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created',
        ),
        migrations.RemoveField(
            model_name='user',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated',
        ),
    ]
