# Generated by Django 4.0 on 2026-03-06 18:43

import uuid

from django.db import migrations, models
import django.utils.timezone


def _populate_user_public_ids(apps, schema_editor):
    User = apps.get_model("core_user", "User")
    users = []
    for user in User.objects.filter(public_id__isnull=True).iterator():
        user.public_id = uuid.uuid4()
        users.append(user)
    if users:
        User.objects.bulk_update(users, ["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0004_user_posts_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='public_id',
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=_populate_user_public_ids,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
